name: induk_club_promotion_app_project
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get: ^4.6.5
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  hidden_drawer_menu: ^3.0.1
  image_picker: ^1.0.4
  kakao_flutter_sdk_user: ^1.7.0
  rive: ^0.11.17
  side_navigation: ^1.0.4
  sign_in_with_apple: ^5.0.0
  smooth_page_indicator: ^1.1.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/rives/
    - assets/gifs/
    - assets/images/
