// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Vl1Oxu3xc2EE5aX-lFQM3XHfawVmKFM',
    appId: '1:1075088512102:web:a28e31c201d4e6301c49a7',
    messagingSenderId: '1075088512102',
    projectId: 'idcp-app',
    authDomain: 'idcp-app.firebaseapp.com',
    storageBucket: 'idcp-app.appspot.com',
    measurementId: 'G-6ZJ3KKCJVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqtd3f31ZTQrfIwKbrp9DueRkJnvcaESA',
    appId: '1:1075088512102:android:e4f19b41340273161c49a7',
    messagingSenderId: '1075088512102',
    projectId: 'idcp-app',
    storageBucket: 'idcp-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHWJqclskZ4ejhlOrxYbJcAZ3xN-UKHk',
    appId: '1:1075088512102:ios:a4148e76cb7f0e991c49a7',
    messagingSenderId: '1075088512102',
    projectId: 'idcp-app',
    storageBucket: 'idcp-app.appspot.com',
    iosBundleId: 'com.example.indukClubPromotionAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHWJqclskZ4ejhlOrxYbJcAZ3xN-UKHk',
    appId: '1:1075088512102:ios:34baa56c337129a51c49a7',
    messagingSenderId: '1075088512102',
    projectId: 'idcp-app',
    storageBucket: 'idcp-app.appspot.com',
    iosBundleId: 'com.example.indukClubPromotionAppProject.RunnerTests',
  );
}
